Repository skyra-project/char, pull requests merged in 2020-07, with the labels that each got.

#4 feat: web bundling through rollup
  .all-contributorsrc
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/SECURITY.md
  .vscode/launch.json
  README.md
  package.json
  rollup.config.ts
  tsconfig.base.json
  tsconfig.eslint.json
  yarn.lock
Labels: Meta: Dependencies, Meta: Documentation, Meta: Feature, Meta: Refactor, Priority: High

#8 refactor: remove Node.js's APIs
  package.json
  rollup.config.ts
  src/lib/Char.ts
  src/lib/CharUnicodeInfo.ts
  src/lib/CharUnicodeInfo/CategoriesValues.ts
  src/lib/CharUnicodeInfo/CategoryCasingDataLevel1.ts
  src/lib/CharUnicodeInfo/CategoryCasingDataLevel2.ts
  src/lib/CharUnicodeInfo/CategoryCasingDataLevel3.ts
  src/lib/CharUnicodeInfo/DigitValues.ts
  src/lib/CharUnicodeInfo/NumericGrapheneDataLevel1.ts
  src/lib/CharUnicodeInfo/NumericGrapheneDataLevel2.ts
  src/lib/CharUnicodeInfo/NumericGrapheneDataLevel3.ts
  src/lib/CharUnicodeInfo/NumericValues.ts
  src/lib/TypedArrayUtilities.ts
  yarn.lock
Labels: Meta: Refactor, Priority: Medium

#9 test: increase coverage
  src/lib/Char.ts
  tests/getNumericValue.test.ts
  tests/getUnicodeCategory.test.ts
  tests/isControl.test.ts
  tests/isDigit.test.ts
Labels: Meta: BugFix, Meta: Refactor, Priority: Medium
